version: "3.7"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./server/.env.prod
    depends_on:
      - products-db
    volumes:
      - static:/home/app/web/staticfiles
  products-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=products
      - POSTGRES_PASSWORD=products
      - POSTGRES_DB=products_dev
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env.prod
    # command: npm install --production && npm run build
    container_name: nginx
    depends_on:
      - server
      # - products-db
    ports:
      - 80:80
    volumes:
      - static:/staticfiles
      - static:/usr/share/nginx/html/static
volumes:
  postgres_data:
  static:
    driver: local
